-- ----------------------------------------------
-- DDL Statements for tables
-- ----------------------------------------------
CREATE TABLE "CUSTOMERS" ("ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "CUSTOMER_NAME" VARCHAR(255), "ACTIVE" VARCHAR(5) NOT NULL default 'Y');

CREATE TABLE "CUSTOMERS_PROFILE" ("CUSTOMER_ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "CUSTOMER_ADDRESS" VARCHAR(255), "CUSTOMER_EMAIL" VARCHAR(255));

CREATE TABLE "PURCHASES" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "CUSTOMER_ID" INTEGER, "PURCHASE_DATE" TIMESTAMP, "ACTIVE" VARCHAR(5) NOT NULL default 'Y');

CREATE TABLE "PRODUCT" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(20), "CATEGORY" VARCHAR(20), "DESCRIPTION" VARCHAR(255), "IMAGEURI" VARCHAR(40), "PRICE" DECIMAL(10, 2));

CREATE TABLE "PURCHASE_PRODUCT" ("PURCHASEID" INTEGER NOT NULL , "PRODUCTID" INTEGER NOT NULL );

-- ----------------------------------------------
-- DDL Statements for keys
-- ----------------------------------------------

-- primary/unique
--ALTER TABLE "PURCHASES" ADD CONSTRAINT "SQL120325130144010" PRIMARY KEY ("ID");
--ALTER TABLE "CUSTOMERS" ADD CONSTRAINT "SQL120325130144011" PRIMARY KEY ("ID");
--ALTER TABLE "PRODUCT" ADD CONSTRAINT "SQL120325130144012" PRIMARY KEY ("PRODUCTID");

--one to one
ALTER TABLE "CUSTOMERS" ADD CONSTRAINT "SQL120325130144011" UNIQUE ("ID");

ALTER TABLE "CUSTOMERS_PROFILE" ADD CONSTRAINT "SQL120325130144012" UNIQUE ("CUSTOMER_ID");
ALTER TABLE "CUSTOMERS_PROFILE" ADD FOREIGN KEY(CUSTOMER_ID) REFERENCES "CUSTOMERS"(ID);

--many to one
ALTER TABLE "PURCHASES" ADD CONSTRAINT "SQL120325130144013" UNIQUE ("ID");
ALTER TABLE "PURCHASES" ADD FOREIGN KEY(CUSTOMER_ID) REFERENCES "CUSTOMERS"(ID);

ALTER TABLE "PRODUCT" ADD CONSTRAINT "SQL120325130144014" UNIQUE("ID");

-- many to many
ALTER TABLE "PURCHASE_PRODUCT" ADD CONSTRAINT "SQL120325130144015" UNIQUE("PURCHASEID", "PRODUCTID");
ALTER TABLE "PURCHASE_PRODUCT" ADD FOREIGN KEY(PURCHASEID) REFERENCES "PURCHASES"(ID);
ALTER TABLE "PURCHASE_PRODUCT" ADD FOREIGN KEY(PRODUCTID) REFERENCES "PRODUCT"(ID);
